### ISSUE TITLE
Reducing the size of a Node.js app section does not make sense.

### ISSUE THREAD

**Issue by jthomas** [IBM-Bluemix-Docs/openwhisk#104]
The section here does not make sense: 
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-creating-javascript-actions#large-app-reduce

This section looks like it should give you instructions on building a custom base image with extra Node.js modules baked in. I think lots of stuff has been missed off as the current docs make no sense.

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've removed these sections until the content can be updated.
