### ISSUE TITLE
Result and Parameters values are now 5MB not 1MB.

### ISSUE THREAD

**Issue by jthomas** [IBM-Bluemix-Docs/openwhisk#105]
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-openwhisk_reference#openwhisk_reference

**Comment by derekpoindexter** [comment]
updated the `result` and `parameter` values here: https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-openwhisk_reference#openwhisk_reference
