### ISSUE TITLE
There is no step 6 in the CLI instructions - ow_watson_discovery.md

### ISSUE THREAD

**Issue by RezaOwliaei** [IBM-Bluemix-Docs/openwhisk#107]
You are referring to steps 5 and 6 in 8th step of "[Installing from the Cloud Functions UI](https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-discovery-package#discovery_ui)" document, which is invalid:

> To bind service credentials to all actions in the package, follow steps 5 and 6 in the CLI instructions listed above.

There's no 6th step.

**Comment by derekpoindexter** [comment]
This should've pointed to step 4. I've updated the doc. https://github.com/IBM-Bluemix-Docs/openwhisk/pull/108
