### ISSUE TITLE
remove api-experimental from docs

### ISSUE THREAD

**Issue by csantanapr** [IBM-Bluemix-Docs/openwhisk#11]
the api-experimental has being removed now and deploy to production.
please remove the following note
```
**Note: The APIs you created using the wsk api-experimental will continue to work for a short period, however you should begin migrating your APIs to web actions and reconfigure your existing apis using the new CLI command wsk api.**
```
from openwhisk_apigateway.md

cc @mdeuser

**Comment by jpkessle** [comment]
The note has been removed from staging and prod and will be available after the next build.

**Comment by jpkessle** [comment]
Updates are live and look good:

API Gateway
https://console.bluemix.net/docs/openwhisk/openwhisk_apigateway.html#openwhisk_apigateway
