### ISSUE TITLE
Customer Satisfaction Issues from New doc style removing listing of runtime libraries in images

### ISSUE THREAD

**Issue by davetropeano** [IBM-Bluemix-Docs/openwhisk#119]
In the doc migration there was a decision to remove the direct listing of runtime libraries supported for a given version of the programming language. This is driving negative NPS and customer comments and should be changed back to the old approach.

For example, the old doc was located here: https://console.bluemix.net/docs/openwhisk/openwhisk_reference.html#openwhisk_reference

The new doc does have any mention of libraries on the systems limit page. Instead there is a runtimes page here: https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-runtimes#runtimes

The user has to click on a CHANGELOG.md file link and scroll in order to get a list of libraries. 

This is non-intuitive and again causing satisfaction issues. We should *immediately* go back to the old approach of listing the libraries per programming language version.

**Comment by derekpoindexter** [comment]
Added package lists to the Runtimes topic= https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-runtimes#runtimes
