### ISSUE TITLE
update web actions now take json string

### ISSUE THREAD

**Issue by csantanapr** [IBM-Bluemix-Docs/openwhisk#12]
change to webactions.md have being landed in open.
Update once it's promoted to staging and production next week I would ETA.
Here is the change:
https://github.com/apache/incubator-openwhisk/pull/2609/files#diff-444445a530f5b36d76f58f15f9220f49

**Comment by jpkessle** [comment]
Testing changes on staging now. Will review after next build. 
Promoting to prod once code is deployed (eta next week) 

Staging review:

Web Actions
https://console.stage1.bluemix.net/docs/openwhisk/openwhisk_webactions.html#openwhisk_webactions

**Comment by jpkessle** [comment]
Checked with devs, code is not yet deployed to prod. Will continue holding off prod updates for now. 
Will check again after next promotion.

**Comment by jpkessle** [comment]
Confirmed with devs the code has been deployed, updated prod doc.
