### ISSUE TITLE
Left hand nav menu in docs has HTML that isn't rendering

### ISSUE THREAD

**Issue by davetropeano** [IBM-Bluemix-Docs/openwhisk#155]
In the left hand nav menu for the docs on the Getting Started page I see this:

![image](https://user-images.githubusercontent.com/1832614/61408807-e6b66600-a8ae-11e9-8370-4f7c4be9d4cd.png)

the `&reg;` isn't rendering as a trademark symbol in Chrome. Version 75.0.3770.142 (Official Build) (64-bit) on OSX

**Comment by derekpoindexter** [comment]
fix is live
